"""
models.py — Pydantic response models for SmartShala.

Defines the JSON schemas that LLM output is validated against.
Used by intent.py (IntentResult) and content.py (ExplainResponse, QuizResponse).
"""

from pydantic import BaseModel, field_validator


class IntentResult(BaseModel):
    """Result of intent extraction from a teacher's spoken transcript."""

    mode: str  # "explain" | "quiz" | "unclear"
    topic: str | None = None

    @field_validator("mode")
    @classmethod
    def validate_mode(cls, v: str) -> str:
        allowed = ("explain", "quiz", "unclear")
        if v not in allowed:
            raise ValueError(f"mode must be one of {allowed}, got '{v}'")
        return v


class ExplainResponse(BaseModel):
    """Structured Hinglish explanation generated by the LLM."""

    topic: str
    explanation: str
    key_points: list[str]


class QuizQuestion(BaseModel):
    """A single multiple-choice question."""

    question: str
    options: list[str]  # exactly 4 options
    correct_index: int  # 0–3
    explanation: str

    @field_validator("correct_index")
    @classmethod
    def validate_correct_index(cls, v: int) -> int:
        if not 0 <= v <= 3:
            raise ValueError(f"correct_index must be 0–3, got {v}")
        return v

    @field_validator("options")
    @classmethod
    def validate_options_count(cls, v: list[str]) -> list[str]:
        if len(v) != 4:
            raise ValueError(f"Must have exactly 4 options, got {len(v)}")
        return v


class QuizResponse(BaseModel):
    """Structured quiz (multiple MCQs) generated by the LLM."""

    topic: str
    questions: list[QuizQuestion]  # 3–5 questions
